// src/app/constants/country-codes.ts
export const COUNTRY_CODES = [
  { name: 'Afghanistan', dialCode: '+93', code: 'AF', flag: 'https://flagcdn.com/24x18/af.png' },
  { name: 'Albania', dialCode: '+355', code: 'AL', flag: 'https://flagcdn.com/24x18/al.png' },
  { name: 'Algeria', dialCode: '+213', code: 'DZ', flag: 'https://flagcdn.com/24x18/dz.png' },
  { name: 'Andorra', dialCode: '+376', code: 'AD', flag: 'https://flagcdn.com/24x18/ad.png' },
  { name: 'Angola', dialCode: '+244', code: 'AO', flag: 'https://flagcdn.com/24x18/ao.png' },
  { name: 'Antigua and Barbuda', dialCode: '+1-268', code: 'AG', flag: 'https://flagcdn.com/24x18/ag.png' },
  { name: 'Argentina', dialCode: '+54', code: 'AR', flag: 'https://flagcdn.com/24x18/ar.png' },
  { name: 'Armenia', dialCode: '+374', code: 'AM', flag: 'https://flagcdn.com/24x18/am.png' },
  { name: 'Australia', dialCode: '+61', code: 'AU', flag: 'https://flagcdn.com/24x18/au.png' },
  { name: 'Austria', dialCode: '+43', code: 'AT', flag: 'https://flagcdn.com/24x18/at.png' },
  { name: 'Azerbaijan', dialCode: '+994', code: 'AZ', flag: 'https://flagcdn.com/24x18/az.png' },
  { name: 'Bahamas', dialCode: '+1-242', code: 'BS', flag: 'https://flagcdn.com/24x18/bs.png' },
  { name: 'Bahrain', dialCode: '+973', code: 'BH', flag: 'https://flagcdn.com/24x18/bh.png' },
  { name: 'Bangladesh', dialCode: '+880', code: 'BD', flag: 'https://flagcdn.com/24x18/bd.png' },
  { name: 'Barbados', dialCode: '+1-246', code: 'BB', flag: 'https://flagcdn.com/24x18/bb.png' },
  { name: 'Belarus', dialCode: '+375', code: 'BY', flag: 'https://flagcdn.com/24x18/by.png' },
  { name: 'Belgium', dialCode: '+32', code: 'BE', flag: 'https://flagcdn.com/24x18/be.png' },
  { name: 'Belize', dialCode: '+501', code: 'BZ', flag: 'https://flagcdn.com/24x18/bz.png' },
  { name: 'Benin', dialCode: '+229', code: 'BJ', flag: 'https://flagcdn.com/24x18/bj.png' },
  { name: 'Bhutan', dialCode: '+975', code: 'BT', flag: 'https://flagcdn.com/24x18/bt.png' },
  { name: 'Bolivia', dialCode: '+591', code: 'BO', flag: 'https://flagcdn.com/24x18/bo.png' },
  { name: 'Bosnia and Herzegovina', dialCode: '+387', code: 'BA', flag: 'https://flagcdn.com/24x18/ba.png' },
  { name: 'Botswana', dialCode: '+267', code: 'BW', flag: 'https://flagcdn.com/24x18/bw.png' },
  { name: 'Brazil', dialCode: '+55', code: 'BR', flag: 'https://flagcdn.com/24x18/br.png' },
  { name: 'Brunei', dialCode: '+673', code: 'BN', flag: 'https://flagcdn.com/24x18/bn.png' },
  { name: 'Bulgaria', dialCode: '+359', code: 'BG', flag: 'https://flagcdn.com/24x18/bg.png' },
  { name: 'Burkina Faso', dialCode: '+226', code: 'BF', flag: 'https://flagcdn.com/24x18/bf.png' },
  { name: 'Burundi', dialCode: '+257', code: 'BI', flag: 'https://flagcdn.com/24x18/bi.png' },
  { name: 'Cambodia', dialCode: '+855', code: 'KH', flag: 'https://flagcdn.com/24x18/kh.png' },
  { name: 'Cameroon', dialCode: '+237', code: 'CM', flag: 'https://flagcdn.com/24x18/cm.png' },
  { name: 'Canada', dialCode: '+1', code: 'CA', flag: 'https://flagcdn.com/24x18/ca.png' },
  { name: 'Cape Verde', dialCode: '+238', code: 'CV', flag: 'https://flagcdn.com/24x18/cv.png' },
  { name: 'Central African Republic', dialCode: '+236', code: 'CF', flag: 'https://flagcdn.com/24x18/cf.png' },
  { name: 'Chad', dialCode: '+235', code: 'TD', flag: 'https://flagcdn.com/24x18/td.png' },
  { name: 'Chile', dialCode: '+56', code: 'CL', flag: 'https://flagcdn.com/24x18/cl.png' },
  { name: 'China', dialCode: '+86', code: 'CN', flag: 'https://flagcdn.com/24x18/cn.png' },
  { name: 'Colombia', dialCode: '+57', code: 'CO', flag: 'https://flagcdn.com/24x18/co.png' },
  { name: 'Comoros', dialCode: '+269', code: 'KM', flag: 'https://flagcdn.com/24x18/km.png' },
  { name: 'Congo (Republic)', dialCode: '+242', code: 'CG', flag: 'https://flagcdn.com/24x18/cg.png' },
  { name: 'Congo (DRC)', dialCode: '+243', code: 'CD', flag: 'https://flagcdn.com/24x18/cd.png' },
  { name: 'Costa Rica', dialCode: '+506', code: 'CR', flag: 'https://flagcdn.com/24x18/cr.png' },
  { name: 'Côte d\'Ivoire', dialCode: '+225', code: 'CI', flag: 'https://flagcdn.com/24x18/ci.png' },
  { name: 'Croatia', dialCode: '+385', code: 'HR', flag: 'https://flagcdn.com/24x18/hr.png' },
  { name: 'Cuba', dialCode: '+53', code: 'CU', flag: 'https://flagcdn.com/24x18/cu.png' },
  { name: 'Cyprus', dialCode: '+357', code: 'CY', flag: 'https://flagcdn.com/24x18/cy.png' },
  { name: 'Czech Republic', dialCode: '+420', code: 'CZ', flag: 'https://flagcdn.com/24x18/cz.png' },
  { name: 'Denmark', dialCode: '+45', code: 'DK', flag: 'https://flagcdn.com/24x18/dk.png' },
  { name: 'Djibouti', dialCode: '+253', code: 'DJ', flag: 'https://flagcdn.com/24x18/dj.png' },
  { name: 'Dominica', dialCode: '+1-767', code: 'DM', flag: 'https://flagcdn.com/24x18/dm.png' },
  { name: 'Dominican Republic', dialCode: '+1-809', code: 'DO', flag: 'https://flagcdn.com/24x18/do.png' },
  { name: 'Ecuador', dialCode: '+593', code: 'EC', flag: 'https://flagcdn.com/24x18/ec.png' },
  { name: 'Egypt', dialCode: '+20', code: 'EG', flag: 'https://flagcdn.com/24x18/eg.png' },
  { name: 'El Salvador', dialCode: '+503', code: 'SV', flag: 'https://flagcdn.com/24x18/sv.png' },
  { name: 'Equatorial Guinea', dialCode: '+240', code: 'GQ', flag: 'https://flagcdn.com/24x18/gq.png' },
  { name: 'Eritrea', dialCode: '+291', code: 'ER', flag: 'https://flagcdn.com/24x18/er.png' },
  { name: 'Estonia', dialCode: '+372', code: 'EE', flag: 'https://flagcdn.com/24x18/ee.png' },
  { name: 'Eswatini', dialCode: '+268', code: 'SZ', flag: 'https://flagcdn.com/24x18/sz.png' },
  { name: 'Ethiopia', dialCode: '+251', code: 'ET', flag: 'https://flagcdn.com/24x18/et.png' },
  { name: 'Fiji', dialCode: '+679', code: 'FJ', flag: 'https://flagcdn.com/24x18/fj.png' },
  { name: 'Finland', dialCode: '+358', code: 'FI', flag: 'https://flagcdn.com/24x18/fi.png' },
  { name: 'France', dialCode: '+33', code: 'FR', flag: 'https://flagcdn.com/24x18/fr.png' },
  { name: 'Gabon', dialCode: '+241', code: 'GA', flag: 'https://flagcdn.com/24x18/ga.png' },
  { name: 'Gambia', dialCode: '+220', code: 'GM', flag: 'https://flagcdn.com/24x18/gm.png' },
  { name: 'Georgia', dialCode: '+995', code: 'GE', flag: 'https://flagcdn.com/24x18/ge.png' },
  { name: 'Germany', dialCode: '+49', code: 'DE', flag: 'https://flagcdn.com/24x18/de.png' },
  { name: 'Ghana', dialCode: '+233', code: 'GH', flag: 'https://flagcdn.com/24x18/gh.png' },
  { name: 'Greece', dialCode: '+30', code: 'GR', flag: 'https://flagcdn.com/24x18/gr.png' },
  { name: 'Grenada', dialCode: '+1-473', code: 'GD', flag: 'https://flagcdn.com/24x18/gd.png' },
  { name: 'Guatemala', dialCode: '+502', code: 'GT', flag: 'https://flagcdn.com/24x18/gt.png' },
  { name: 'Guinea', dialCode: '+224', code: 'GN', flag: 'https://flagcdn.com/24x18/gn.png' },
  { name: 'Guinea-Bissau', dialCode: '+245', code: 'GW', flag: 'https://flagcdn.com/24x18/gw.png' },
  { name: 'Guyana', dialCode: '+592', code: 'GY', flag: 'https://flagcdn.com/24x18/gy.png' },
  { name: 'Haiti', dialCode: '+509', code: 'HT', flag: 'https://flagcdn.com/24x18/ht.png' },
  { name: 'Honduras', dialCode: '+504', code: 'HN', flag: 'https://flagcdn.com/24x18/hn.png' },
  { name: 'Hungary', dialCode: '+36', code: 'HU', flag: 'https://flagcdn.com/24x18/hu.png' },
  { name: 'Iceland', dialCode: '+354', code: 'IS', flag: 'https://flagcdn.com/24x18/is.png' },
  { name: 'India', dialCode: '+91', code: 'IN', flag: 'https://flagcdn.com/24x18/in.png' },
  { name: 'Indonesia', dialCode: '+62', code: 'ID', flag: 'https://flagcdn.com/24x18/id.png' },
  { name: 'Iran', dialCode: '+98', code: 'IR', flag: 'https://flagcdn.com/24x18/ir.png' },
  { name: 'Iraq', dialCode: '+964', code: 'IQ', flag: 'https://flagcdn.com/24x18/iq.png' },
  { name: 'Ireland', dialCode: '+353', code: 'IE', flag: 'https://flagcdn.com/24x18/ie.png' },
  { name: 'Israel', dialCode: '+972', code: 'IL', flag: 'https://flagcdn.com/24x18/il.png' },
  { name: 'Italy', dialCode: '+39', code: 'IT', flag: 'https://flagcdn.com/24x18/it.png' },
  { name: 'Jamaica', dialCode: '+1-876', code: 'JM', flag: 'https://flagcdn.com/24x18/jm.png' },
  { name: 'Japan', dialCode: '+81', code: 'JP', flag: 'https://flagcdn.com/24x18/jp.png' },
  { name: 'Jordan', dialCode: '+962', code: 'JO', flag: 'https://flagcdn.com/24x18/jo.png' },
  { name: 'Kazakhstan', dialCode: '+7', code: 'KZ', flag: 'https://flagcdn.com/24x18/kz.png' },
  { name: 'Kenya', dialCode: '+254', code: 'KE', flag: 'https://flagcdn.com/24x18/ke.png' },
  { name: 'Kiribati', dialCode: '+686', code: 'KI', flag: 'https://flagcdn.com/24x18/ki.png' },
  { name: 'Korea, North', dialCode: '+850', code: 'KP', flag: 'https://flagcdn.com/24x18/kp.png' },
  { name: 'Korea, South', dialCode: '+82', code: 'KR', flag: 'https://flagcdn.com/24x18/kr.png' },
  { name: 'Kosovo', dialCode: '+383', code: 'XK', flag: 'https://flagcdn.com/24x18/xk.png' },
  { name: 'Kuwait', dialCode: '+965', code: 'KW', flag: 'https://flagcdn.com/24x18/kw.png' },
  { name: 'Kyrgyzstan', dialCode: '+996', code: 'KG', flag: 'https://flagcdn.com/24x18/kg.png' },
  { name: 'Laos', dialCode: '+856', code: 'LA', flag: 'https://flagcdn.com/24x18/la.png' },
  { name: 'Latvia', dialCode: '+371', code: 'LV', flag: 'https://flagcdn.com/24x18/lv.png' },
  { name: 'Lebanon', dialCode: '+961', code: 'LB', flag: 'https://flagcdn.com/24x18/lb.png' },
  { name: 'Lesotho', dialCode: '+266', code: 'LS', flag: 'https://flagcdn.com/24x18/ls.png' },
  { name: 'Liberia', dialCode: '+231', code: 'LR', flag: 'https://flagcdn.com/24x18/lr.png' },
  { name: 'Libya', dialCode: '+218', code: 'LY', flag: 'https://flagcdn.com/24x18/ly.png' },
  { name: 'Liechtenstein', dialCode: '+423', code: 'LI', flag: 'https://flagcdn.com/24x18/li.png' },
  { name: 'Lithuania', dialCode: '+370', code: 'LT', flag: 'https://flagcdn.com/24x18/lt.png' },
  { name: 'Luxembourg', dialCode: '+352', code: 'LU', flag: 'https://flagcdn.com/24x18/lu.png' },
  { name: 'Madagascar', dialCode: '+261', code: 'MG', flag: 'https://flagcdn.com/24x18/mg.png' },
  { name: 'Malawi', dialCode: '+265', code: 'MW', flag: 'https://flagcdn.com/24x18/mw.png' },
  { name: 'Malaysia', dialCode: '+60', code: 'MY', flag: 'https://flagcdn.com/24x18/my.png' },
  { name: 'Maldives', dialCode: '+960', code: 'MV', flag: 'https://flagcdn.com/24x18/mv.png' },
  { name: 'Mali', dialCode: '+223', code: 'ML', flag: 'https://flagcdn.com/24x18/ml.png' },
  { name: 'Malta', dialCode: '+356', code: 'MT', flag: 'https://flagcdn.com/24x18/mt.png' },
  { name: 'Marshall Islands', dialCode: '+692', code: 'MH', flag: 'https://flagcdn.com/24x18/mh.png' },
  { name: 'Mauritania', dialCode: '+222', code: 'MR', flag: 'https://flagcdn.com/24x18/mr.png' },
  { name: 'Mauritius', dialCode: '+230', code: 'MU', flag: 'https://flagcdn.com/24x18/mu.png' },
  { name: 'Mexico', dialCode: '+52', code: 'MX', flag: 'https://flagcdn.com/24x18/mx.png' },
  { name: 'Micronesia', dialCode: '+691', code: 'FM', flag: 'https://flagcdn.com/24x18/fm.png' },
  { name: 'Moldova', dialCode: '+373', code: 'MD', flag: 'https://flagcdn.com/24x18/md.png' },
  { name: 'Monaco', dialCode: '+377', code: 'MC', flag: 'https://flagcdn.com/24x18/mc.png' },
  { name: 'Mongolia', dialCode: '+976', code: 'MN', flag: 'https://flagcdn.com/24x18/mn.png' },
  { name: 'Montenegro', dialCode: '+382', code: 'ME', flag: 'https://flagcdn.com/24x18/me.png' },
  { name: 'Morocco', dialCode: '+212', code: 'MA', flag: 'https://flagcdn.com/24x18/ma.png' },
  { name: 'Mozambique', dialCode: '+258', code: 'MZ', flag: 'https://flagcdn.com/24x18/mz.png' },
  { name: 'Myanmar', dialCode: '+95', code: 'MM', flag: 'https://flagcdn.com/24x18/mm.png' },
  { name: 'Namibia', dialCode: '+264', code: 'NA', flag: 'https://flagcdn.com/24x18/na.png' },
  { name: 'Nauru', dialCode: '+674', code: 'NR', flag: 'https://flagcdn.com/24x18/nr.png' },
  { name: 'Nepal', dialCode: '+977', code: 'NP', flag: 'https://flagcdn.com/24x18/np.png' },
  { name: 'Netherlands', dialCode: '+31', code: 'NL', flag: 'https://flagcdn.com/24x18/nl.png' },
  { name: 'New Zealand', dialCode: '+64', code: 'NZ', flag: 'https://flagcdn.com/24x18/nz.png' },
  { name: 'Nicaragua', dialCode: '+505', code: 'NI', flag: 'https://flagcdn.com/24x18/ni.png' },
  { name: 'Niger', dialCode: '+227', code: 'NE', flag: 'https://flagcdn.com/24x18/ne.png' },
  { name: 'Nigeria', dialCode: '+234', code: 'NG', flag: 'https://flagcdn.com/24x18/ng.png' },
  { name: 'North Macedonia', dialCode: '+389', code: 'MK', flag: 'https://flagcdn.com/24x18/mk.png' },
  { name: 'Norway', dialCode: '+47', code: 'NO', flag: 'https://flagcdn.com/24x18/no.png' },
  { name: 'Oman', dialCode: '+968', code: 'OM', flag: 'https://flagcdn.com/24x18/om.png' },
  { name: 'Pakistan', dialCode: '+92', code: 'PK', flag: 'https://flagcdn.com/24x18/pk.png' },
  { name: 'Palau', dialCode: '+680', code: 'PW', flag: 'https://flagcdn.com/24x18/pw.png' },
  { name: 'Palestine', dialCode: '+970', code: 'PS', flag: 'https://flagcdn.com/24x18/ps.png' },
  { name: 'Panama', dialCode: '+507', code: 'PA', flag: 'https://flagcdn.com/24x18/pa.png' },
  { name: 'Papua New Guinea', dialCode: '+675', code: 'PG', flag: 'https://flagcdn.com/24x18/pg.png' },
  { name: 'Paraguay', dialCode: '+595', code: 'PY', flag: 'https://flagcdn.com/24x18/py.png' },
  { name: 'Peru', dialCode: '+51', code: 'PE', flag: 'https://flagcdn.com/24x18/pe.png' },
  { name: 'Philippines', dialCode: '+63', code: 'PH', flag: 'https://flagcdn.com/24x18/ph.png' },
  { name: 'Poland', dialCode: '+48', code: 'PL', flag: 'https://flagcdn.com/24x18/pl.png' },
  { name: 'Portugal', dialCode: '+351', code: 'PT', flag: 'https://flagcdn.com/24x18/pt.png' },
  { name: 'Qatar', dialCode: '+974', code: 'QA', flag: 'https://flagcdn.com/24x18/qa.png' },
  { name: 'Romania', dialCode: '+40', code: 'RO', flag: 'https://flagcdn.com/24x18/ro.png' },
  { name: 'Russia', dialCode: '+7', code: 'RU', flag: 'https://flagcdn.com/24x18/ru.png' },
  { name: 'Rwanda', dialCode: '+250', code: 'RW', flag: 'https://flagcdn.com/24x18/rw.png' },
  { name: 'Saint Kitts and Nevis', dialCode: '+1-869', code: 'KN', flag: 'https://flagcdn.com/24x18/kn.png' },
  { name: 'Saint Lucia', dialCode: '+1-758', code: 'LC', flag: 'https://flagcdn.com/24x18/lc.png' },
  { name: 'Saint Vincent and the Grenadines', dialCode: '+1-784', code: 'VC', flag: 'https://flagcdn.com/24x18/vc.png' },
  { name: 'Samoa', dialCode: '+685', code: 'WS', flag: 'https://flagcdn.com/24x18/ws.png' },
  { name: 'San Marino', dialCode: '+378', code: 'SM', flag: 'https://flagcdn.com/24x18/sm.png' },
  { name: 'Sao Tome and Principe', dialCode: '+239', code: 'ST', flag: 'https://flagcdn.com/24x18/st.png' },
  { name: 'Saudi Arabia', dialCode: '+966', code: 'SA', flag: 'https://flagcdn.com/24x18/sa.png' },
  { name: 'Senegal', dialCode: '+221', code: 'SN', flag: 'https://flagcdn.com/24x18/sn.png' },
  { name: 'Serbia', dialCode: '+381', code: 'RS', flag: 'https://flagcdn.com/24x18/rs.png' },
  { name: 'Seychelles', dialCode: '+248', code: 'SC', flag: 'https://flagcdn.com/24x18/sc.png' },
  { name: 'Sierra Leone', dialCode: '+232', code: 'SL', flag: 'https://flagcdn.com/24x18/sl.png' },
  { name: 'Singapore', dialCode: '+65', code: 'SG', flag: 'https://flagcdn.com/24x18/sg.png' },
  { name: 'Slovakia', dialCode: '+421', code: 'SK', flag: 'https://flagcdn.com/24x18/sk.png' },
  { name: 'Slovenia', dialCode: '+386', code: 'SI', flag: 'https://flagcdn.com/24x18/si.png' },
  { name: 'Solomon Islands', dialCode: '+677', code: 'SB', flag: 'https://flagcdn.com/24x18/sb.png' },
  { name: 'Somalia', dialCode: '+252', code: 'SO', flag: 'https://flagcdn.com/24x18/so.png' },
  { name: 'South Africa', dialCode: '+27', code: 'ZA', flag: 'https://flagcdn.com/24x18/za.png' },
  { name: 'South Sudan', dialCode: '+211', code: 'SS', flag: 'https://flagcdn.com/24x18/ss.png' },
  { name: 'Spain', dialCode: '+34', code: 'ES', flag: 'https://flagcdn.com/24x18/es.png' },
  { name: 'Sri Lanka', dialCode: '+94', code: 'LK', flag: 'https://flagcdn.com/24x18/lk.png' },
  { name: 'Sudan', dialCode: '+249', code: 'SD', flag: 'https://flagcdn.com/24x18/sd.png' },
  { name: 'Suriname', dialCode: '+597', code: 'SR', flag: 'https://flagcdn.com/24x18/sr.png' },
  { name: 'Sweden', dialCode: '+46', code: 'SE', flag: 'https://flagcdn.com/24x18/se.png' },
  { name: 'Switzerland', dialCode: '+41', code: 'CH', flag: 'https://flagcdn.com/24x18/ch.png' },
  { name: 'Syria', dialCode: '+963', code: 'SY', flag: 'https://flagcdn.com/24x18/sy.png' },
  { name: 'Taiwan', dialCode: '+886', code: 'TW', flag: 'https://flagcdn.com/24x18/tw.png' },
  { name: 'Tajikistan', dialCode: '+992', code: 'TJ', flag: 'https://flagcdn.com/24x18/tj.png' },
  { name: 'Tanzania', dialCode: '+255', code: 'TZ', flag: 'https://flagcdn.com/24x18/tz.png' },
  { name: 'Thailand', dialCode: '+66', code: 'TH', flag: 'https://flagcdn.com/24x18/th.png' },
  { name: 'Timor-Leste', dialCode: '+670', code: 'TL', flag: 'https://flagcdn.com/24x18/tl.png' },
  { name: 'Togo', dialCode: '+228', code: 'TG', flag: 'https://flagcdn.com/24x18/tg.png' },
  { name: 'Tonga', dialCode: '+676', code: 'TO', flag: 'https://flagcdn.com/24x18/to.png' },
  { name: 'Trinidad and Tobago', dialCode: '+1-868', code: 'TT', flag: 'https://flagcdn.com/24x18/tt.png' },
  { name: 'Tunisia', dialCode: '+216', code: 'TN', flag: 'https://flagcdn.com/24x18/tn.png' },
  { name: 'Turkey', dialCode: '+90', code: 'TR', flag: 'https://flagcdn.com/24x18/tr.png' },
  { name: 'Turkmenistan', dialCode: '+993', code: 'TM', flag: 'https://flagcdn.com/24x18/tm.png' },
  { name: 'Tuvalu', dialCode: '+688', code: 'TV', flag: 'https://flagcdn.com/24x18/tv.png' },
  { name: 'Uganda', dialCode: '+256', code: 'UG', flag: 'https://flagcdn.com/24x18/ug.png' },
  { name: 'Ukraine', dialCode: '+380', code: 'UA', flag: 'https://flagcdn.com/24x18/ua.png' },
  { name: 'United Arab Emirates', dialCode: '+971', code: 'AE', flag: 'https://flagcdn.com/24x18/ae.png' },
  { name: 'United Kingdom', dialCode: '+44', code: 'GB', flag: 'https://flagcdn.com/24x18/gb.png' },
  { name: 'United States', dialCode: '+1', code: 'US', flag: 'https://flagcdn.com/24x18/us.png' },
  { name: 'Uruguay', dialCode: '+598', code: 'UY', flag: 'https://flagcdn.com/24x18/uy.png' },
]